name: collapsible_side_menu_example
description: "Demonstrate how to use collapsible_side_menu package."

publish_to: 'none' # This ensures the example app won't be published to pub.dev

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  collapsible_side_menu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
