name: Publish package to pub.dev

on:
  # push:
  #   branches: [master]
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]'
  #     - 'v[0-9]+.[0-9]+.[0-9]+*+'
  release:
    types: [published] # triggers when you create a GitHub Release
  workflow_dispatch: # allows manual trigger from GitHub Actions tab

# This ensures that previous jobs for the PR are canceled when PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    # permissions:
    #   id-token: write # Required for authentication using OIDC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # - name: Validate package (dry run)
      #   run: flutter pub publish --dry-run

      - name: Publish
        # run: flutter pub publish --force
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          credentialJson: ${{ secrets.PUB_CREDENTIALS }}
          format: true
          skipTests: true
